# Generated by Django 6.0.5 on 2026-05-17 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('status', models.CharField(choices=[('history', 'Project History'), ('live', 'Live Projects'), ('upcoming', 'Upcoming Projects')], max_length=20)),
                ('project_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PROJECTS', max_length=200)),
                ('hero_image', models.ImageField(upload_to='projects/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', ckeditor.fields.RichTextField()),
                ('bullet_points', models.TextField(help_text='Enter each point in new line')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_content', ckeditor.fields.RichTextField()),
                ('center_image', models.ImageField(upload_to='services/intro/')),
                ('right_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='slider/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='social_services/')),
                ('status', models.CharField(choices=[('history', 'Service History'), ('ongoing', 'Ongoing Services'), ('upcoming', 'Upcoming Services')], max_length=20)),
                ('project_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-project_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOCIAL SERVICES', max_length=200)),
                ('hero_image', models.ImageField(upload_to='social_services/hero/')),
            ],
        ),
    ]
