# Generated by Django 6.0.5 on 2026-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_careerhero_companyculture_hrcontact_internship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='CareerHero',
        ),
        migrations.DeleteModel(
            name='CompanyCulture',
        ),
        migrations.DeleteModel(
            name='HRContact',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='WhyJoinUs',
        ),
        migrations.DeleteModel(
            name='CareerApplication',
        ),
        migrations.DeleteModel(
            name='JobOpening',
        ),
    ]
