# Generated by Django 6.0.5 on 2026-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_careerapplication_job_delete_careerhero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/hero/videos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/'),
        ),
        migrations.AddField(
            model_name='servicepageintro',
            name='center_video',
            field=models.FileField(blank=True, null=True, upload_to='services/intro/videos/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slider/videos/'),
        ),
        migrations.AddField(
            model_name='socialservice',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social_services/videos/'),
        ),
        migrations.AddField(
            model_name='socialservicespage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='social_services/hero/videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepageintro',
            name='center_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/intro/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_services/'),
        ),
        migrations.AlterField(
            model_name='socialservicespage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_services/hero/'),
        ),
    ]
